### ISSUE TITLE
Lock NFT in L1 (Bridge L1->L2)

### ISSUE THREAD

**Issue by remiroyc** [ScreenshotLabs/starklane#43]
## L1 -> L2 

The ```deposit``` function of the L1 smart contract must transfer the user's NFT before sending a message to the L2 smart contract to replicate the NFT on Starknet. 

 The "lock system" enables the bridge to work in both directions. The L1 smart contract will temporarily be the owner of the original NFT until the bridge operation is carried out in reverse (allowing the user to retrieve their NFT on L1 when they have locked the copy on L2).

**Comment by kwiss** [comment]
Should we deploy a contract to hold the assets per collection on the L1 to mitigate the risks ?
